CREATE TABLE "tbl_Lehrer" ("LehrerID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 0)  NOT NULL PRIMARY KEY,
					   "Nachnname" VARCHAR(150),
					   "Vorname" VARCHAR(150),
					   "GebDatum" DATE)

CREATE TABLE "tbl_Fachbereiche"("FachbereichID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 0)  NOT NULL PRIMARY KEY,
                                                    "Name" VARCHAR(150))

CREATE TABLE "tbl_Altersteilzeit"("AltersteilzeitID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 0)  NOT NULL PRIMARY KEY,
                                                 "Bezeichung" VARCHAR(150),
						 "Alter" DOUBLE,
						 "Wochenstunden" DOUBLE,
						 "Stichtag" DATE)
						 
CREATE TABLE "tbl_Entlastungsstunden"("EntlastungsstundenID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 0)  NOT NULL PRIMARY KEY,
                                                           "Bezeichung" VARCHAR(150),
							   "Grund" VARCHAR(500),
							   "Wochenstunden" DOUBLE,
							   "Gesetzlich" BOOLEAN)
							   
CREATE TABLE "tbl_Lehrerstatus"("LehrerID" INTEGER NOT NULL,
						"Halbjahr" VARCHAR(6) NOT NULL,
						"Status_RV" VARCHAR(2),
						"Status_LBF" VARCHAR(2),
						"Status_BSA" VARCHAR(2),
						CONSTRAINT "SYS_PK_tbl_Lehrerstatus" PRIMARY KEY("LehrerID","Halbjahr"),
						CONSTRAINT SYS_FK_1 FOREIGN KEY("LehrerID") REFERENCES "tbl_Lehrer"("LehrerID"))
						
CREATE TABLE "tbl_Lehrerfachbereich"("LehrerID" INTEGER NOT NULL,
							"FachbereichID" INTEGER NOT NULL,
							"Halbjahr" VARCHAR(6) NOT NULL,
							"Wochenstunden" DOUBLE,
							CONSTRAINT "SYS_PK_tbl_Lehrerfachbereich" PRIMARY KEY("LehrerID","FachbereichID","Halbjahr"),
							CONSTRAINT SYS_FK_4 FOREIGN KEY("LehrerID") REFERENCES "tbl_Lehrer"("LehrerID"),
							CONSTRAINT SYS_FK_5 FOREIGN KEY("FachbereichID") REFERENCES "tbl_Fachbereiche"("FachbereichID"))
							
CREATE TABLE "tbl_LehrerEntlastungsstunden"("LehrerID" INTEGER NOT NULL,
									"EntlastungsstundenID" INTEGER NOT NULL,
									"Halbjahr" VARCHAR(6) NOT NULL,
									CONSTRAINT "SYS_PK_tbl_LehrerEntlastungsstunden" PRIMARY KEY("LehrerID","EntlastungsstundenID","Halbjahr"),
									CONSTRAINT SYS_FK_10 FOREIGN KEY("LehrerID") REFERENCES "tbl_Lehrer"("LehrerID"),
									CONSTRAINT SYS_FK_11 FOREIGN KEY("EntlastungsstundenID") REFERENCES "tbl_Entlastungsstunden"("EntlastungsstundenID"))
									
CREATE USER SA PASSWORD "" ADMIN
